SELECT USER FROM dual;

CREATE TABLE APP_USERS (
    ID NUMBER(19),
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    PASSWORD VARCHAR2(255 CHAR) NOT NULL,
    ROLE VARCHAR2(20 CHAR) DEFAULT 'INSTRUCTOR' NOT NULL,
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    
    CONSTRAINT PK_APP_USERS PRIMARY KEY (ID),
    CONSTRAINT UQ_APP_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_APP_USERS_ROLE CHECK (ROLE = 'INSTRUCTOR')
);

CREATE SEQUENCE APP_USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
    
SELECT COLUMN_NAME,
       DATA_TYPE,
       DATA_PRECISION,
       CHAR_LENGTH,
       NULLABLE,
       DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'APP_USERS'
ORDER BY COLUMN_ID;