spring.application.name=classbridge

spring.datasource.url=jdbc:oracle:thin:@//SEUNGJELEE:1522/XEPDB1
spring.datasource.username=classbridge
spring.datasource.password=${CLASSBRIDGE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none